### ISSUE TITLE
s3-photo-resizer is not working for me

### ISSUE THREAD

**Issue by farhanzix** [chrisvoll/s3-photo-resizer#1]
Hi,

I like your library but i tried to use this but this seems to be not me. Can you please help me to reslove this issue.
I used same URL pattern

resize.php?src=/path/to/image/in/s3.jpg&query=640x480.-50

i tried to use Full path of s3 image and only images name itself as well  
src=https://adproject.s3.amazonaws.com/vY9sCq4Xtsg2PKI.png
src=vY9sCq4Xtsg2PKI.png

Every time it loads a blank page.I have a question as well please let me know this libarary resize orignal images as well in s3 bucket?

Thanks
Farhan

**Comment by chrisvoll** [comment]
@farhanzix Hi! This library is no longer actively maintained, so I suggest using a more mature and stable alternative such as [thumbor](https://github.com/thumbor/thumbor).
